export type PreviewErrorCode =
  | 'PREVIEW_CONTRACT_MIGRATION_REQUIRED'
  | 'PREVIEW_CONTRACT_REGISTRY_INVALID'
  | 'INSTALLATION_TRUST_UNAVAILABLE'
  | 'INSTALLATION_IDENTITY_INVALID'
  | 'AUTHORITY_REGISTRY_INVALID'
  | 'PREVIEW_CANONICAL_INVALID'
  | 'PREVIEW_UNKNOWN_FIELD'
  | 'PREVIEW_HASH_INVALID'
  | 'PREVIEW_SCOPE_INVALID'
  | 'PREVIEW_VALIDITY_INVALID'
  | 'PREVIEW_SOURCE_AUTHORITY_MISSING'
  | 'FORMAL_RELEASE_AUTHORITY_MISSING'
  | 'PREVIEW_RELEASE_AUTHORITY_MISSING'
  | 'PREVIEW_APPROVAL_INVALID'
  | 'PREVIEW_APPROVAL_HASH_CONFLICT'
  | 'PREVIEW_PRINCIPAL_INVALID'
  | 'PRINCIPAL_ENROLLMENT_REQUIRED'
  | 'PRINCIPAL_ENROLLMENT_INVALID'
  | 'PRINCIPAL_ROTATION_INVALID'
  | 'PRINCIPAL_MAPPING_EXPIRED'
  | 'PRINCIPAL_MAPPING_REVOKED'
  | 'PRINCIPAL_MAPPING_OVERLAP'
  | 'PRINCIPAL_SEPARATION_OF_DUTIES_FAILED'
  | 'PREVIEW_PRINCIPAL_MAPPING_MISSING'
  | 'PREVIEW_PRINCIPAL_MAPPING_REVOKED'
  | 'PREVIEW_PACK_RELEASE_SEPARATION_OF_DUTIES_FAILED'
  | 'PREVIEW_IDEMPOTENCY_CONFLICT'
  | 'PREVIEW_EVENT_OWNERSHIP_CONFLICT'
  | 'PREVIEW_STATE_CONFLICT'
  | 'PREVIEW_SESSION_CONTRACT_INVALID'
  | 'PREVIEW_RESULT_SUPPRESSED'
  | 'FEEDBACK_COMMIT_ID_COLLISION'
  | 'FEEDBACK_COMMIT_CONFLICT'
  | 'FEEDBACK_REVISION_CONFLICT'
  | 'FEEDBACK_STATE_CONFLICT'
  | 'FEEDBACK_CAPABILITY_INVALID'
  | 'FEEDBACK_RECONCILE_REQUIRED'
  | 'FEEDBACK_PRIVACY_VIOLATION'

export const PREVIEW_ERROR_CODES = Object.freeze([
  'PREVIEW_CONTRACT_MIGRATION_REQUIRED',
  'PREVIEW_CONTRACT_REGISTRY_INVALID',
  'INSTALLATION_TRUST_UNAVAILABLE',
  'INSTALLATION_IDENTITY_INVALID',
  'AUTHORITY_REGISTRY_INVALID',
  'PREVIEW_CANONICAL_INVALID',
  'PREVIEW_UNKNOWN_FIELD',
  'PREVIEW_HASH_INVALID',
  'PREVIEW_SCOPE_INVALID',
  'PREVIEW_VALIDITY_INVALID',
  'PREVIEW_SOURCE_AUTHORITY_MISSING',
  'FORMAL_RELEASE_AUTHORITY_MISSING',
  'PREVIEW_RELEASE_AUTHORITY_MISSING',
  'PREVIEW_APPROVAL_INVALID',
  'PREVIEW_APPROVAL_HASH_CONFLICT',
  'PREVIEW_PRINCIPAL_INVALID',
  'PRINCIPAL_ENROLLMENT_REQUIRED',
  'PRINCIPAL_ENROLLMENT_INVALID',
  'PRINCIPAL_ROTATION_INVALID',
  'PRINCIPAL_MAPPING_EXPIRED',
  'PRINCIPAL_MAPPING_REVOKED',
  'PRINCIPAL_MAPPING_OVERLAP',
  'PRINCIPAL_SEPARATION_OF_DUTIES_FAILED',
  'PREVIEW_PRINCIPAL_MAPPING_MISSING',
  'PREVIEW_PRINCIPAL_MAPPING_REVOKED',
  'PREVIEW_PACK_RELEASE_SEPARATION_OF_DUTIES_FAILED',
  'PREVIEW_IDEMPOTENCY_CONFLICT',
  'PREVIEW_EVENT_OWNERSHIP_CONFLICT',
  'PREVIEW_STATE_CONFLICT',
  'PREVIEW_SESSION_CONTRACT_INVALID',
  'PREVIEW_RESULT_SUPPRESSED',
  'FEEDBACK_COMMIT_ID_COLLISION',
  'FEEDBACK_COMMIT_CONFLICT',
  'FEEDBACK_REVISION_CONFLICT',
  'FEEDBACK_STATE_CONFLICT',
  'FEEDBACK_CAPABILITY_INVALID',
  'FEEDBACK_RECONCILE_REQUIRED',
  'FEEDBACK_PRIVACY_VIOLATION'
] as const satisfies readonly PreviewErrorCode[])
